/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Allan
 */
public class TelaAlunos extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    public TelaAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiasAluno = new javax.swing.JTabbedPane();
        guiaVisualizarAluno = new javax.swing.JPanel();
        tituloVisualizarFunc = new javax.swing.JLabel();
        botaoVoltar6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        painelConsulta1 = new javax.swing.JPanel();
        tituloConsultar1 = new javax.swing.JLabel();
        tituloCpf4 = new javax.swing.JLabel();
        campoPesquisarCpfFunc1 = new javax.swing.JTextField();
        botaoPesquisar1 = new javax.swing.JButton();
        tituloAlunos1 = new javax.swing.JLabel();
        tituloNome2 = new javax.swing.JLabel();
        tituloCpf3 = new javax.swing.JLabel();
        tituloDataNasc2 = new javax.swing.JLabel();
        tituloCurso2 = new javax.swing.JLabel();
        tituloCurso3 = new javax.swing.JLabel();
        tituloCurso4 = new javax.swing.JLabel();
        tituloCurso5 = new javax.swing.JLabel();
        tituloDataNasc9 = new javax.swing.JLabel();
        tituloDataNasc10 = new javax.swing.JLabel();
        tituloCurso14 = new javax.swing.JLabel();
        guiaEditarAluno = new javax.swing.JPanel();
        painelConsulta2 = new javax.swing.JPanel();
        tituloConsultar2 = new javax.swing.JLabel();
        tituloCpf5 = new javax.swing.JLabel();
        campoPesquisarCpfFunc2 = new javax.swing.JTextField();
        botaoPesquisar2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        tituloVisualizarFunc1 = new javax.swing.JLabel();
        botaoVoltar8 = new javax.swing.JButton();
        botaoVoltar9 = new javax.swing.JButton();
        tituloAlunos2 = new javax.swing.JLabel();
        campoNome4 = new javax.swing.JTextField();
        tituloNome4 = new javax.swing.JLabel();
        tituloCpf7 = new javax.swing.JLabel();
        campoCpf4 = new javax.swing.JTextField();
        campoDataNasc10 = new javax.swing.JFormattedTextField();
        tituloDataNasc4 = new javax.swing.JLabel();
        campoDataNasc11 = new javax.swing.JFormattedTextField();
        campoDataNasc12 = new javax.swing.JFormattedTextField();
        tituloCurso10 = new javax.swing.JLabel();
        tituloCurso11 = new javax.swing.JLabel();
        campoDataNasc13 = new javax.swing.JFormattedTextField();
        tituloCurso12 = new javax.swing.JLabel();
        campoCurso4 = new javax.swing.JComboBox();
        tituloCurso13 = new javax.swing.JLabel();
        campoDataNasc14 = new javax.swing.JFormattedTextField();
        tituloDataNasc5 = new javax.swing.JLabel();
        campoDataNasc15 = new javax.swing.JFormattedTextField();
        tituloDataNasc6 = new javax.swing.JLabel();
        guiaCadastrarAluno = new javax.swing.JPanel();
        tituloCadastrar = new javax.swing.JLabel();
        botaoCadastrar1 = new javax.swing.JButton();
        botaoVoltar5 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tituloAlunos3 = new javax.swing.JLabel();
        campoDataNasc6 = new javax.swing.JFormattedTextField();
        tituloCurso6 = new javax.swing.JLabel();
        tituloCurso7 = new javax.swing.JLabel();
        campoDataNasc7 = new javax.swing.JFormattedTextField();
        campoDataNasc8 = new javax.swing.JFormattedTextField();
        tituloCurso8 = new javax.swing.JLabel();
        campoCurso3 = new javax.swing.JComboBox();
        campoNome3 = new javax.swing.JTextField();
        campoCpf3 = new javax.swing.JTextField();
        campoDataNasc9 = new javax.swing.JFormattedTextField();
        tituloDataNasc3 = new javax.swing.JLabel();
        tituloCpf6 = new javax.swing.JLabel();
        tituloNome3 = new javax.swing.JLabel();
        tituloCurso9 = new javax.swing.JLabel();
        campoDataNasc16 = new javax.swing.JFormattedTextField();
        tituloDataNasc7 = new javax.swing.JLabel();
        tituloDataNasc8 = new javax.swing.JLabel();
        campoDataNasc17 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guiasAluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tituloVisualizarFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloVisualizarFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVisualizarFunc.setText("Aluno");
        tituloVisualizarFunc.setToolTipText("");
        tituloVisualizarFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botaoVoltar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/back.png"))); // NOI18N
        botaoVoltar6.setText("Voltar");
        botaoVoltar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar6ActionPerformed(evt);
            }
        });

        painelConsulta1.setBackground(new java.awt.Color(222, 235, 216));
        painelConsulta1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        painelConsulta1.setForeground(new java.awt.Color(204, 204, 204));
        painelConsulta1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tituloConsultar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloConsultar1.setText("Consultar Aluno");

        tituloCpf4.setText("Código: ");

        botaoPesquisar1.setBackground(new java.awt.Color(255, 255, 255));
        botaoPesquisar1.setForeground(new java.awt.Color(255, 255, 255));
        botaoPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/search.png"))); // NOI18N
        botaoPesquisar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoPesquisar1.setBorderPainted(false);
        botaoPesquisar1.setContentAreaFilled(false);
        botaoPesquisar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsulta1Layout = new javax.swing.GroupLayout(painelConsulta1);
        painelConsulta1.setLayout(painelConsulta1Layout);
        painelConsulta1Layout.setHorizontalGroup(
            painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta1Layout.createSequentialGroup()
                .addGroup(painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsulta1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(tituloConsultar1))
                    .addGroup(painelConsulta1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloCpf4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPesquisarCpfFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelConsulta1Layout.setVerticalGroup(
            painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta1Layout.createSequentialGroup()
                .addComponent(tituloConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsulta1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCpf4)
                            .addComponent(campoPesquisarCpfFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelConsulta1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisar1))))
        );

        tituloAlunos1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloAlunos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/alunos.png"))); // NOI18N
        tituloAlunos1.setText("  Manter Alunos");

        tituloNome2.setText("Nome:");

        tituloCpf3.setText("Cpf:");

        tituloDataNasc2.setText("Data de Nascimento:");

        tituloCurso2.setText("Curso:");

        tituloCurso3.setText("Inicio:");

        tituloCurso4.setText("Previsão de Término:");

        tituloCurso5.setText("Status:");

        tituloDataNasc9.setText("Email:");

        tituloDataNasc10.setText("Telefone:");

        tituloCurso14.setText("Cartão:");

        javax.swing.GroupLayout guiaVisualizarAlunoLayout = new javax.swing.GroupLayout(guiaVisualizarAluno);
        guiaVisualizarAluno.setLayout(guiaVisualizarAlunoLayout);
        guiaVisualizarAlunoLayout.setHorizontalGroup(
            guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltar6)
                    .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tituloCurso14)
                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaVisualizarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloAlunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(painelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tituloVisualizarFunc)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(tituloCpf3)
                                        .addGap(358, 358, 358))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tituloNome2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloDataNasc10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloDataNasc9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloCurso5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(123, 123, 123))
                            .addComponent(tituloDataNasc2))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        guiaVisualizarAlunoLayout.setVerticalGroup(
            guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAlunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloVisualizarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNome2)
                    .addComponent(tituloCurso2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf3)
                    .addComponent(tituloCurso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                        .addComponent(tituloCurso4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloCurso5))
                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                        .addComponent(tituloDataNasc9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloDataNasc10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(tituloDataNasc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloCurso14)
                .addGap(29, 29, 29)
                .addComponent(botaoVoltar6)
                .addGap(23, 23, 23))
        );

        guiasAluno.addTab("Visualizar Aluno", guiaVisualizarAluno);

        painelConsulta2.setBackground(new java.awt.Color(222, 235, 216));
        painelConsulta2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        painelConsulta2.setForeground(new java.awt.Color(204, 204, 204));
        painelConsulta2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tituloConsultar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloConsultar2.setText("Consultar Aluno");

        tituloCpf5.setText("Código: ");

        botaoPesquisar2.setBackground(new java.awt.Color(255, 255, 255));
        botaoPesquisar2.setForeground(new java.awt.Color(255, 255, 255));
        botaoPesquisar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/search.png"))); // NOI18N
        botaoPesquisar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoPesquisar2.setBorderPainted(false);
        botaoPesquisar2.setContentAreaFilled(false);
        botaoPesquisar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsulta2Layout = new javax.swing.GroupLayout(painelConsulta2);
        painelConsulta2.setLayout(painelConsulta2Layout);
        painelConsulta2Layout.setHorizontalGroup(
            painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta2Layout.createSequentialGroup()
                .addGroup(painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsulta2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(tituloConsultar2))
                    .addGroup(painelConsulta2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloCpf5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPesquisarCpfFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelConsulta2Layout.setVerticalGroup(
            painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta2Layout.createSequentialGroup()
                .addComponent(tituloConsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsulta2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCpf5)
                            .addComponent(campoPesquisarCpfFunc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelConsulta2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisar2))))
        );

        tituloVisualizarFunc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloVisualizarFunc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVisualizarFunc1.setText("Aluno");
        tituloVisualizarFunc1.setToolTipText("");
        tituloVisualizarFunc1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botaoVoltar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/edit.png"))); // NOI18N
        botaoVoltar8.setText("Salvar Alterações");

        botaoVoltar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/back.png"))); // NOI18N
        botaoVoltar9.setText("Voltar");
        botaoVoltar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar9ActionPerformed(evt);
            }
        });

        tituloAlunos2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloAlunos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/alunos.png"))); // NOI18N
        tituloAlunos2.setText("  Manter Alunos");

        campoNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNome4ActionPerformed(evt);
            }
        });

        tituloNome4.setText("Nome:");

        tituloCpf7.setText("Cpf:");

        campoCpf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpf4ActionPerformed(evt);
            }
        });

        campoDataNasc10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc10.setToolTipText("Date");
        campoDataNasc10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc4.setText("Data de Nascimento:");

        campoDataNasc11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc11.setToolTipText("Date");
        campoDataNasc11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        campoDataNasc12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc12.setToolTipText("Date");
        campoDataNasc12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloCurso10.setText("Status:");

        tituloCurso11.setText("Previsão de Término:");

        campoDataNasc13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc13.setToolTipText("Date");
        campoDataNasc13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloCurso12.setText("Inicio:");

        campoCurso4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Sistemas de Informação", "Ciência da Computação", "Licenciatura em Informática" }));

        tituloCurso13.setText("Curso:");

        campoDataNasc14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc14.setToolTipText("Date");
        campoDataNasc14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc5.setText("Telefone:");

        campoDataNasc15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc15.setToolTipText("Date");
        campoDataNasc15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc6.setText("Email:");

        javax.swing.GroupLayout guiaEditarAlunoLayout = new javax.swing.GroupLayout(guiaEditarAluno);
        guiaEditarAluno.setLayout(guiaEditarAlunoLayout);
        guiaEditarAlunoLayout.setHorizontalGroup(
            guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                            .addComponent(botaoVoltar9)
                            .addGap(18, 18, 18)
                            .addComponent(botaoVoltar8))
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloAlunos2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(painelConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tituloVisualizarFunc1)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloNome4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNome4))
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloCpf7)
                                .addGap(14, 14, 14)
                                .addComponent(campoCpf4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloDataNasc4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoDataNasc10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloDataNasc5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoDataNasc14))
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloDataNasc6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoDataNasc15)))
                        .addGap(34, 34, 34)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloCurso13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCurso4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloCurso10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoDataNasc12)
                                    .addComponent(campoDataNasc13)
                                    .addComponent(campoDataNasc11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        guiaEditarAlunoLayout.setVerticalGroup(
            guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAlunos2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloVisualizarFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNome4)
                    .addComponent(campoNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloCurso13)
                    .addComponent(campoCurso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf7)
                    .addComponent(campoCpf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloCurso12)
                    .addComponent(campoDataNasc13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCurso11)
                    .addComponent(campoDataNasc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloDataNasc6)
                    .addComponent(campoDataNasc15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCurso10)
                    .addComponent(campoDataNasc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloDataNasc5)
                    .addComponent(campoDataNasc14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloDataNasc4)
                    .addComponent(campoDataNasc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar9)
                    .addComponent(botaoVoltar8))
                .addGap(24, 24, 24))
        );

        guiasAluno.addTab("Editar Aluno", guiaEditarAluno);

        tituloCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCadastrar.setText("Cadastrar Novo Aluno");
        tituloCadastrar.setToolTipText("");
        tituloCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botaoCadastrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoCadastrar1.setText("Salvar");
        botaoCadastrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botaoVoltar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/back.png"))); // NOI18N
        botaoVoltar5.setText("Voltar");
        botaoVoltar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar5ActionPerformed(evt);
            }
        });

        tituloAlunos3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloAlunos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/alunos.png"))); // NOI18N
        tituloAlunos3.setText("  Manter Alunos");

        campoDataNasc6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc6.setToolTipText("Date");
        campoDataNasc6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloCurso6.setText("Status:");

        tituloCurso7.setText("Previsão de Término:");

        campoDataNasc7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc7.setToolTipText("Date");
        campoDataNasc7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        campoDataNasc8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc8.setToolTipText("Date");
        campoDataNasc8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloCurso8.setText("Inicio:");

        campoCurso3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Sistemas de Informação", "Ciência da Computação", "Licenciatura em Informática" }));

        campoNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNome3ActionPerformed(evt);
            }
        });

        campoCpf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpf3ActionPerformed(evt);
            }
        });

        campoDataNasc9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc9.setToolTipText("Date");
        campoDataNasc9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc3.setText("Data de Nascimento:");

        tituloCpf6.setText("Cpf:");

        tituloNome3.setText("Nome:");

        tituloCurso9.setText("Curso:");

        campoDataNasc16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc16.setToolTipText("Date");
        campoDataNasc16.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc7.setText("Telefone:");

        tituloDataNasc8.setText("Email:");

        campoDataNasc17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoDataNasc17.setToolTipText("Date");
        campoDataNasc17.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout guiaCadastrarAlunoLayout = new javax.swing.GroupLayout(guiaCadastrarAluno);
        guiaCadastrarAluno.setLayout(guiaCadastrarAlunoLayout);
        guiaCadastrarAlunoLayout.setHorizontalGroup(
            guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltar5)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrar1)
                .addGap(26, 26, 26))
            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloAlunos3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCadastrar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloNome3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNome3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloDataNasc3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoDataNasc9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloDataNasc7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoDataNasc16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloCpf6)
                                            .addComponent(tituloDataNasc8))
                                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(campoCpf3))
                                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campoDataNasc17, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(tituloCurso8)
                                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campoDataNasc8))
                                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(tituloCurso6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campoDataNasc6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(tituloCurso9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoCurso3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaCadastrarAlunoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tituloCurso7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoDataNasc7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        guiaCadastrarAlunoLayout.setVerticalGroup(
            guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloAlunos3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNome3)
                    .addComponent(campoNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCurso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloCurso9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf6)
                    .addComponent(campoCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloCurso8)
                    .addComponent(campoDataNasc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCurso7)
                            .addComponent(campoDataNasc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCurso6)
                            .addComponent(campoDataNasc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoVoltar5)))
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloDataNasc8)
                            .addComponent(campoDataNasc17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDataNasc7)
                            .addComponent(campoDataNasc16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDataNasc3)
                            .addComponent(campoDataNasc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        campoNome3.getAccessibleContext().setAccessibleName("txtCadNomeAluno");
        campoNome3.getAccessibleContext().setAccessibleDescription("");

        guiasAluno.addTab("Cadastrar Novo Aluno", guiaCadastrarAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiasAluno)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiasAluno)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisar1ActionPerformed

    private void botaoPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisar2ActionPerformed

    private void botaoVoltar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar5ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltar5ActionPerformed

    private void botaoVoltar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar9ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltar9ActionPerformed

    private void botaoVoltar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltar6ActionPerformed

    private void campoNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNome3ActionPerformed

    private void campoCpf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpf3ActionPerformed

    private void campoNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNome4ActionPerformed

    private void campoCpf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpf4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlunos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar1;
    private javax.swing.JButton botaoPesquisar1;
    private javax.swing.JButton botaoPesquisar2;
    private javax.swing.JButton botaoVoltar5;
    private javax.swing.JButton botaoVoltar6;
    private javax.swing.JButton botaoVoltar8;
    private javax.swing.JButton botaoVoltar9;
    private javax.swing.JTextField campoCpf3;
    private javax.swing.JTextField campoCpf4;
    private javax.swing.JComboBox campoCurso3;
    private javax.swing.JComboBox campoCurso4;
    private javax.swing.JFormattedTextField campoDataNasc10;
    private javax.swing.JFormattedTextField campoDataNasc11;
    private javax.swing.JFormattedTextField campoDataNasc12;
    private javax.swing.JFormattedTextField campoDataNasc13;
    private javax.swing.JFormattedTextField campoDataNasc14;
    private javax.swing.JFormattedTextField campoDataNasc15;
    private javax.swing.JFormattedTextField campoDataNasc16;
    private javax.swing.JFormattedTextField campoDataNasc17;
    private javax.swing.JFormattedTextField campoDataNasc6;
    private javax.swing.JFormattedTextField campoDataNasc7;
    private javax.swing.JFormattedTextField campoDataNasc8;
    private javax.swing.JFormattedTextField campoDataNasc9;
    private javax.swing.JTextField campoNome3;
    private javax.swing.JTextField campoNome4;
    private javax.swing.JTextField campoPesquisarCpfFunc1;
    private javax.swing.JTextField campoPesquisarCpfFunc2;
    private javax.swing.JPanel guiaCadastrarAluno;
    private javax.swing.JPanel guiaEditarAluno;
    private javax.swing.JPanel guiaVisualizarAluno;
    private javax.swing.JTabbedPane guiasAluno;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel painelConsulta1;
    private javax.swing.JPanel painelConsulta2;
    private javax.swing.JLabel tituloAlunos1;
    private javax.swing.JLabel tituloAlunos2;
    private javax.swing.JLabel tituloAlunos3;
    private javax.swing.JLabel tituloCadastrar;
    private javax.swing.JLabel tituloConsultar1;
    private javax.swing.JLabel tituloConsultar2;
    private javax.swing.JLabel tituloCpf3;
    private javax.swing.JLabel tituloCpf4;
    private javax.swing.JLabel tituloCpf5;
    private javax.swing.JLabel tituloCpf6;
    private javax.swing.JLabel tituloCpf7;
    private javax.swing.JLabel tituloCurso10;
    private javax.swing.JLabel tituloCurso11;
    private javax.swing.JLabel tituloCurso12;
    private javax.swing.JLabel tituloCurso13;
    private javax.swing.JLabel tituloCurso14;
    private javax.swing.JLabel tituloCurso2;
    private javax.swing.JLabel tituloCurso3;
    private javax.swing.JLabel tituloCurso4;
    private javax.swing.JLabel tituloCurso5;
    private javax.swing.JLabel tituloCurso6;
    private javax.swing.JLabel tituloCurso7;
    private javax.swing.JLabel tituloCurso8;
    private javax.swing.JLabel tituloCurso9;
    private javax.swing.JLabel tituloDataNasc10;
    private javax.swing.JLabel tituloDataNasc2;
    private javax.swing.JLabel tituloDataNasc3;
    private javax.swing.JLabel tituloDataNasc4;
    private javax.swing.JLabel tituloDataNasc5;
    private javax.swing.JLabel tituloDataNasc6;
    private javax.swing.JLabel tituloDataNasc7;
    private javax.swing.JLabel tituloDataNasc8;
    private javax.swing.JLabel tituloDataNasc9;
    private javax.swing.JLabel tituloNome2;
    private javax.swing.JLabel tituloNome3;
    private javax.swing.JLabel tituloNome4;
    private javax.swing.JLabel tituloVisualizarFunc;
    private javax.swing.JLabel tituloVisualizarFunc1;
    // End of variables declaration//GEN-END:variables
}
