/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.RepositorioCursos;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import negocio.Aluno;
import negocio.CadastroCursos;
import negocio.Curso;
import negocio.Fachada;
import util.Formatacao;
import util.Validacao;

/**
 *
 * @author Allan
 */
public class TelaAlunos extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    //private RepositorioCursos repositorioCursos = new RepositorioCursos();
    //private CadastroCursos cadastroCursos= new CadastroCursos(repositorioCursos);
    
    private Fachada fachada = Fachada.obterInstancia();
    
    public TelaAlunos() {
        initComponents();
        
        //preenchendo combobox
        this.preencherComboBoxCursoCadastrar();
        this.preencherComboBoxCursoEditar();
        btnExcluirAluno.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void preencherComboBoxCursoCadastrar(){
        List<Curso> allCursos = fachada.listarCursos();
        for (Curso curso : allCursos) {
            //jComboBoxCursoCadastrar.addItem(curso.toString(curso));
            jComboBoxCursoCadastrar.addItem(curso.getNome());
            
        } 
    }
    
    private void preencherComboBoxCursoEditar(){
        List<Curso> allCursos = fachada.listarCursos();
        for (Curso curso : allCursos) {
            jComboBoxCursoEditar.addItem(curso.getNome());
        }
    }
    
    private void pegarDadosCamposCadastrar(){
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiasAluno = new javax.swing.JTabbedPane();
        guiaEditarAluno = new javax.swing.JPanel();
        painelConsulta2 = new javax.swing.JPanel();
        tituloConsultar2 = new javax.swing.JLabel();
        tituloCpf5 = new javax.swing.JLabel();
        btnPesquisarCpfEditar = new javax.swing.JButton();
        txtPesquisarCpfEditar = new javax.swing.JFormattedTextField();
        jSeparator5 = new javax.swing.JSeparator();
        tituloVisualizarFunc1 = new javax.swing.JLabel();
        btnSalvarAlteracoes = new javax.swing.JButton();
        botaoVoltar9 = new javax.swing.JButton();
        tituloAlunos2 = new javax.swing.JLabel();
        tituloNome4 = new javax.swing.JLabel();
        tituloCpf7 = new javax.swing.JLabel();
        tituloDataNasc4 = new javax.swing.JLabel();
        tituloCurso10 = new javax.swing.JLabel();
        tituloCurso11 = new javax.swing.JLabel();
        tituloCurso12 = new javax.swing.JLabel();
        tituloCurso13 = new javax.swing.JLabel();
        tituloDataNasc5 = new javax.swing.JLabel();
        tituloDataNasc6 = new javax.swing.JLabel();
        jComboBoxStatusEditar = new javax.swing.JComboBox();
        jComboBoxCursoEditar = new javax.swing.JComboBox();
        jTextFieldTelefoneEditar = new javax.swing.JFormattedTextField();
        jTextFieldEmailEditar = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpfEditar = new javax.swing.JFormattedTextField();
        jTextFieldNomeEditar = new javax.swing.JTextField();
        jFormattedTextFieldDataNascEditar = new javax.swing.JFormattedTextField();
        jFormattedTextFieldInicioCursoEditar = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTermCursoEditar = new javax.swing.JFormattedTextField();
        guiaCadastrarAluno = new javax.swing.JPanel();
        tituloCadastrar = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        botaoVoltar5 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tituloAlunos3 = new javax.swing.JLabel();
        tituloCurso6 = new javax.swing.JLabel();
        tituloCurso7 = new javax.swing.JLabel();
        jFormattedTextFieldTermCursoCadastrar = new javax.swing.JFormattedTextField();
        jFormattedTextFieldInicioCursoCadastrar = new javax.swing.JFormattedTextField();
        tituloCurso8 = new javax.swing.JLabel();
        jComboBoxCursoCadastrar = new javax.swing.JComboBox();
        jTextFieldNomeCadastrar = new javax.swing.JTextField();
        jFormattedTextFieldDataNascCadastrar = new javax.swing.JFormattedTextField();
        tituloDataNasc3 = new javax.swing.JLabel();
        tituloCpf6 = new javax.swing.JLabel();
        tituloNome3 = new javax.swing.JLabel();
        tituloCurso9 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JFormattedTextField();
        tituloDataNasc7 = new javax.swing.JLabel();
        tituloDataNasc8 = new javax.swing.JLabel();
        jComboBoxStatusCadastrar = new javax.swing.JComboBox();
        jFormattedTextFieldCpfCadastrar = new javax.swing.JFormattedTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        guiaVisualizarAluno = new javax.swing.JPanel();
        tituloVisualizarFunc = new javax.swing.JLabel();
        botaoVoltar6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        painelConsulta1 = new javax.swing.JPanel();
        tituloConsultar1 = new javax.swing.JLabel();
        tituloCpf4 = new javax.swing.JLabel();
        botaoPesquisar1 = new javax.swing.JButton();
        campoCpfPesquisaVisualizar = new javax.swing.JFormattedTextField();
        tituloAlunos1 = new javax.swing.JLabel();
        tituloNome2 = new javax.swing.JLabel();
        tituloCpf3 = new javax.swing.JLabel();
        tituloDataNasc2 = new javax.swing.JLabel();
        tituloCurso2 = new javax.swing.JLabel();
        tituloCurso3 = new javax.swing.JLabel();
        tituloCurso4 = new javax.swing.JLabel();
        tituloCurso5 = new javax.swing.JLabel();
        tituloDataNasc9 = new javax.swing.JLabel();
        tituloDataNasc10 = new javax.swing.JLabel();
        tituloCurso14 = new javax.swing.JLabel();
        btnExcluirAluno = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblCartao = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblInicioCurso = new javax.swing.JLabel();
        lblTerminoCurso = new javax.swing.JLabel();
        lblStatusAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyTicket - MANTER ALUNO");
        setResizable(false);

        guiasAluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        painelConsulta2.setBackground(new java.awt.Color(222, 235, 216));
        painelConsulta2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        painelConsulta2.setForeground(new java.awt.Color(204, 204, 204));
        painelConsulta2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tituloConsultar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloConsultar2.setText("Consultar Aluno");

        tituloCpf5.setText("CPF:");

        btnPesquisarCpfEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisarCpfEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarCpfEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/search.png"))); // NOI18N
        btnPesquisarCpfEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarCpfEditar.setBorderPainted(false);
        btnPesquisarCpfEditar.setContentAreaFilled(false);
        btnPesquisarCpfEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarCpfEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCpfEditarActionPerformed(evt);
            }
        });

        try {
            txtPesquisarCpfEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelConsulta2Layout = new javax.swing.GroupLayout(painelConsulta2);
        painelConsulta2.setLayout(painelConsulta2Layout);
        painelConsulta2Layout.setHorizontalGroup(
            painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta2Layout.createSequentialGroup()
                .addGroup(painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsulta2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(tituloConsultar2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelConsulta2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloCpf5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisarCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelConsulta2Layout.setVerticalGroup(
            painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta2Layout.createSequentialGroup()
                .addComponent(tituloConsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(painelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf5)
                    .addComponent(txtPesquisarCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addComponent(btnPesquisarCpfEditar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tituloVisualizarFunc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloVisualizarFunc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVisualizarFunc1.setText("Editar Aluno");
        tituloVisualizarFunc1.setToolTipText("");
        tituloVisualizarFunc1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSalvarAlteracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/edit.png"))); // NOI18N
        btnSalvarAlteracoes.setText("Salvar Alterações");

        botaoVoltar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/back.png"))); // NOI18N
        botaoVoltar9.setText("Voltar");
        botaoVoltar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar9ActionPerformed(evt);
            }
        });

        tituloAlunos2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloAlunos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/alunos.png"))); // NOI18N
        tituloAlunos2.setText(" Aluno");

        tituloNome4.setText("Nome:");

        tituloCpf7.setText("Cpf:");

        tituloDataNasc4.setText("Data de Nascimento:");

        tituloCurso10.setText("Status:");

        tituloCurso11.setText("Previsão de Término:");

        tituloCurso12.setText("Início Curso:");

        tituloCurso13.setText("Curso:");

        tituloDataNasc5.setText("Telefone:");

        tituloDataNasc6.setText("Email:");

        jComboBoxStatusEditar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));
        jComboBoxStatusEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusEditarActionPerformed(evt);
            }
        });

        try {
            jTextFieldTelefoneEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldTelefoneEditar.setToolTipText("Date");
        jTextFieldTelefoneEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldEmailEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jTextFieldEmailEditar.setToolTipText("Date");
        jTextFieldEmailEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        try {
            jFormattedTextFieldCpfEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextFieldNomeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeEditarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataNascEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNascEditar.setToolTipText("Date");
        jFormattedTextFieldDataNascEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        try {
            jFormattedTextFieldInicioCursoEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldInicioCursoEditar.setToolTipText("Date");
        jFormattedTextFieldInicioCursoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        try {
            jFormattedTextFieldTermCursoEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTermCursoEditar.setToolTipText("Date");
        jFormattedTextFieldTermCursoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout guiaEditarAlunoLayout = new javax.swing.GroupLayout(guiaEditarAluno);
        guiaEditarAluno.setLayout(guiaEditarAlunoLayout);
        guiaEditarAlunoLayout.setHorizontalGroup(
            guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaEditarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addComponent(botaoVoltar9)
                                .addGap(32, 32, 32)
                                .addComponent(btnSalvarAlteracoes))
                            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloNome4)
                                    .addComponent(tituloCpf7)
                                    .addComponent(tituloDataNasc6)
                                    .addComponent(tituloDataNasc5)
                                    .addComponent(tituloCurso13))
                                .addGap(22, 22, 22)
                                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCursoEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTelefoneEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldEmailEditar)
                                    .addComponent(jFormattedTextFieldCpfEditar)
                                    .addComponent(jTextFieldNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso11)
                                    .addComponent(tituloCurso12)
                                    .addComponent(tituloDataNasc4)
                                    .addComponent(tituloCurso10))
                                .addGap(11, 11, 11)
                                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldInicioCursoEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFormattedTextFieldTermCursoEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxStatusEditar, javax.swing.GroupLayout.Alignment.TRAILING, 0, 116, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldDataNascEditar, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(16, 16, 16))
                    .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tituloAlunos2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tituloVisualizarFunc1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        guiaEditarAlunoLayout.setVerticalGroup(
            guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAlunos2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloVisualizarFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldDataNascEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloDataNasc4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldInicioCursoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCurso12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTermCursoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCurso11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxStatusEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCurso10)))
                    .addGroup(guiaEditarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloNome4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCpf7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmailEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloDataNasc6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefoneEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloDataNasc5))
                        .addGap(14, 14, 14)
                        .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCursoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCurso13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(guiaEditarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar9)
                    .addComponent(btnSalvarAlteracoes))
                .addContainerGap())
        );

        guiasAluno.addTab("Editar Aluno", guiaEditarAluno);

        guiaCadastrarAluno.setPreferredSize(new java.awt.Dimension(640, 372));

        tituloCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCadastrar.setText("Cadastrar Novo Aluno");
        tituloCadastrar.setToolTipText("");
        tituloCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        botaoVoltar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/back.png"))); // NOI18N
        botaoVoltar5.setText("Voltar");
        botaoVoltar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar5ActionPerformed(evt);
            }
        });

        tituloAlunos3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloAlunos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/alunos.png"))); // NOI18N
        tituloAlunos3.setText("Aluno");

        tituloCurso6.setText("Status:");

        tituloCurso7.setText("Previsão de Término:");

        try {
            jFormattedTextFieldTermCursoCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTermCursoCadastrar.setToolTipText("Date");
        jFormattedTextFieldTermCursoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        try {
            jFormattedTextFieldInicioCursoCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldInicioCursoCadastrar.setToolTipText("Date");
        jFormattedTextFieldInicioCursoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloCurso8.setText("Início curso:");

        jTextFieldNomeCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCadastrarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataNascCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNascCadastrar.setToolTipText("Date");
        jFormattedTextFieldDataNascCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc3.setText("Data de Nascimento:");

        tituloCpf6.setText("Cpf:");

        tituloNome3.setText("Nome:");

        tituloCurso9.setText("Curso:");

        try {
            jTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldTelefone.setToolTipText("Date");
        jTextFieldTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tituloDataNasc7.setText("Telefone:");

        tituloDataNasc8.setText("Email:");

        jComboBoxStatusCadastrar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));
        jComboBoxStatusCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusCadastrarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCpfCadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout guiaCadastrarAlunoLayout = new javax.swing.GroupLayout(guiaCadastrarAluno);
        guiaCadastrarAluno.setLayout(guiaCadastrarAlunoLayout);
        guiaCadastrarAlunoLayout.setHorizontalGroup(
            guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltar5)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addGap(26, 26, 26))
            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloNome3)
                                    .addComponent(tituloCpf6))
                                .addGap(25, 25, 25)
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldCpfCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNomeCadastrar)))
                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloDataNasc8)
                                    .addComponent(tituloDataNasc7)
                                    .addComponent(tituloCurso9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelefone)
                                    .addComponent(jComboBoxCursoCadastrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEmail))))
                        .addGap(18, 18, 18)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloCurso8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloDataNasc3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldDataNascCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldInicioCursoCadastrar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloCurso7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tituloCurso6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldTermCursoCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jComboBoxStatusCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloAlunos3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCadastrar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3)))
        );

        guiaCadastrarAlunoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxStatusCadastrar, jFormattedTextFieldDataNascCadastrar, jFormattedTextFieldInicioCursoCadastrar, jFormattedTextFieldTermCursoCadastrar});

        guiaCadastrarAlunoLayout.setVerticalGroup(
            guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloAlunos3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNome3)
                    .addComponent(jTextFieldNomeCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloDataNasc3)
                    .addComponent(jFormattedTextFieldDataNascCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf6)
                    .addComponent(tituloCurso8)
                    .addComponent(jFormattedTextFieldInicioCursoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCpfCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCurso7)
                            .addComponent(jFormattedTextFieldTermCursoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCurso6)
                            .addComponent(jComboBoxStatusCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(guiaCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDataNasc8)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDataNasc7)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCursoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCurso9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(guiaCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar5))
                .addContainerGap())
        );

        jTextFieldNomeCadastrar.getAccessibleContext().setAccessibleName("txtCadNomeAluno");
        jTextFieldNomeCadastrar.getAccessibleContext().setAccessibleDescription("");

        guiasAluno.addTab("Cadastrar Novo Aluno", guiaCadastrarAluno);

        tituloVisualizarFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloVisualizarFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVisualizarFunc.setText("Aluno");
        tituloVisualizarFunc.setToolTipText("");
        tituloVisualizarFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botaoVoltar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/back.png"))); // NOI18N
        botaoVoltar6.setText("Voltar");
        botaoVoltar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar6ActionPerformed(evt);
            }
        });

        painelConsulta1.setBackground(new java.awt.Color(222, 235, 216));
        painelConsulta1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        painelConsulta1.setForeground(new java.awt.Color(204, 204, 204));
        painelConsulta1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tituloConsultar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloConsultar1.setText("Consultar Aluno");

        tituloCpf4.setText("CPF:");

        botaoPesquisar1.setBackground(new java.awt.Color(255, 255, 255));
        botaoPesquisar1.setForeground(new java.awt.Color(255, 255, 255));
        botaoPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/search.png"))); // NOI18N
        botaoPesquisar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoPesquisar1.setBorderPainted(false);
        botaoPesquisar1.setContentAreaFilled(false);
        botaoPesquisar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisar1ActionPerformed(evt);
            }
        });

        try {
            campoCpfPesquisaVisualizar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelConsulta1Layout = new javax.swing.GroupLayout(painelConsulta1);
        painelConsulta1.setLayout(painelConsulta1Layout);
        painelConsulta1Layout.setHorizontalGroup(
            painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta1Layout.createSequentialGroup()
                .addGroup(painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsulta1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(tituloConsultar1)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(painelConsulta1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloCpf4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCpfPesquisaVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelConsulta1Layout.setVerticalGroup(
            painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsulta1Layout.createSequentialGroup()
                .addComponent(tituloConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(painelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf4)
                    .addComponent(campoCpfPesquisaVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addComponent(botaoPesquisar1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tituloAlunos1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tituloAlunos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/alunos.png"))); // NOI18N
        tituloAlunos1.setText("  Aluno");

        tituloNome2.setText("Nome:");

        tituloCpf3.setText("Cpf:");

        tituloDataNasc2.setText("Data de Nascimento:");

        tituloCurso2.setText("Curso:");

        tituloCurso3.setText("Inicio:");

        tituloCurso4.setText("Previsão de Término:");

        tituloCurso5.setText("Status:");

        tituloDataNasc9.setText("Email:");

        tituloDataNasc10.setText("Telefone:");

        tituloCurso14.setText("Cartão:");

        btnExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/delete.png"))); // NOI18N
        btnExcluirAluno.setText("Excluir aluno");

        lblNome.setText("jLabel1");

        lblCpf.setText("jLabel2");

        lblEmail.setText("jLabel3");

        lblTelefone.setText("jLabel4");

        lblDataNascimento.setText("jLabel5");

        lblCartao.setText("jLabel6");

        lblCurso.setText("jLabel7");

        lblInicioCurso.setText("jLabel8");

        lblTerminoCurso.setText("jLabel9");

        lblStatusAluno.setText("jLabel10");

        javax.swing.GroupLayout guiaVisualizarAlunoLayout = new javax.swing.GroupLayout(guiaVisualizarAluno);
        guiaVisualizarAluno.setLayout(guiaVisualizarAlunoLayout);
        guiaVisualizarAlunoLayout.setHorizontalGroup(
            guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                        .addComponent(btnExcluirAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoVoltar6))
                    .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                            .addComponent(tituloCurso14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCartao))
                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaVisualizarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloAlunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(painelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tituloVisualizarFunc)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                .addComponent(tituloDataNasc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataNascimento))
                            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(tituloCpf3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCpf)
                                        .addGap(267, 267, 267))
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaVisualizarAlunoLayout.createSequentialGroup()
                                                .addComponent(tituloNome2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblNome))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaVisualizarAlunoLayout.createSequentialGroup()
                                                .addComponent(tituloDataNasc10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTelefone))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, guiaVisualizarAlunoLayout.createSequentialGroup()
                                                .addComponent(tituloDataNasc9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblEmail)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloCurso2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCurso))
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloCurso3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInicioCurso))
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloCurso5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStatusAluno))
                                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                                        .addComponent(tituloCurso4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTerminoCurso)))
                                .addGap(159, 159, 159)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        guiaVisualizarAlunoLayout.setVerticalGroup(
            guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAlunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloVisualizarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNome2)
                    .addComponent(tituloCurso2)
                    .addComponent(lblNome)
                    .addComponent(lblCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCpf3)
                    .addComponent(tituloCurso3)
                    .addComponent(lblCpf)
                    .addComponent(lblInicioCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCurso4)
                            .addComponent(lblTerminoCurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloCurso5)
                            .addComponent(lblStatusAluno)))
                    .addGroup(guiaVisualizarAlunoLayout.createSequentialGroup()
                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDataNasc9)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDataNasc10)
                            .addComponent(lblTelefone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloDataNasc2)
                    .addComponent(lblDataNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCurso14)
                    .addComponent(lblCartao))
                .addGap(29, 29, 29)
                .addGroup(guiaVisualizarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoVoltar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        guiasAluno.addTab("Visualizar Aluno", guiaVisualizarAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiasAluno)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiasAluno)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisar1ActionPerformed
        // TODO add your handling code here:
        if (campoCpfPesquisaVisualizar.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(this,"Informe o CPF do aluno.","VALIDAÇÃO",JOptionPane.ERROR_MESSAGE);
            return;
        } else{
            try{
                
                
                if (fachada.verificarExistenciaAlunoPorCpf(campoCpfPesquisaVisualizar.getText())){
                    Aluno alunoRetorno = new Aluno();
                    alunoRetorno = fachada.findAlunoByCpf(campoCpfPesquisaVisualizar.getText());
                    
                    lblNome.setText(alunoRetorno.getNome());
                    lblCpf.setText(alunoRetorno.getCpf());
                    lblEmail.setText(alunoRetorno.getEmail());
                    lblTelefone.setText(alunoRetorno.getTelefone());
                    
                    lblDataNascimento.setText(Formatacao.transformarDateEmString((Date)alunoRetorno.getDataNascimento()));
                    
                    Curso cursoAluno = new Curso();
                    cursoAluno = fachada.procurarPorIdCurso(alunoRetorno.getIdCurso());
                    lblCurso.setText(cursoAluno.getNome());
                    
                    lblInicioCurso.setText(Formatacao.transformarDateEmString((Date)alunoRetorno.getInicioCursoAluno()));
                    lblTerminoCurso.setText(Formatacao.transformarDateEmString((Date)alunoRetorno.getTerminoCursoAluno()));
                    
                    lblStatusAluno.setText(alunoRetorno.getStatusAluno());
                    
                    campoCpfPesquisaVisualizar.setText("");
                    
                    btnExcluirAluno.setEnabled(true);
                    
            
                } else {
                    JOptionPane.showMessageDialog(this,"Aluno inexistente!","VALIDAÇÃO",JOptionPane.ERROR_MESSAGE);
                    campoCpfPesquisaVisualizar.setText("");
                    
                    return;
                }
            } catch (Exception ex){
                System.out.println("Erro ao pesquisar.");
                JOptionPane.showMessageDialog(this,"Informação inválida!","VALIDAÇÃO",JOptionPane.ERROR_MESSAGE);
                campoCpfPesquisaVisualizar.setText("");
                               
            }
    }//GEN-LAST:event_botaoPesquisar1ActionPerformed

    private void btnPesquisarCpfEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCpfEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarCpfEditarActionPerformed

    private void botaoVoltar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar9ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltar9ActionPerformed

    private void botaoVoltar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltar6ActionPerformed

    private void jComboBoxStatusCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusCadastrarActionPerformed

    private void jTextFieldNomeCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCadastrarActionPerformed

    private void botaoVoltar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar5ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltar5ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:       
        
        try{
            String nome = jTextFieldNomeCadastrar.getText();
            String cpf = jFormattedTextFieldCpfCadastrar.getText();       
            String email =jTextFieldEmail.getText();                 
            String telefone = jTextFieldTelefone.getText();     

            String curso = jComboBoxCursoCadastrar.getSelectedItem().toString();
            int idCurso = fachada.findIdCursoByNome(curso);
            System.out.println(idCurso);
            String status = jComboBoxStatusCadastrar.getSelectedItem().toString();

            String dataNasc = jFormattedTextFieldDataNascCadastrar.getText();
            Date dataNascDate = Formatacao.transformarStringEmDate(dataNasc);
            java.sql.Date sqlDateNasc = Formatacao.transformarDateEmDateSql(dataNascDate);        

            String inicioCurso= jFormattedTextFieldInicioCursoCadastrar.getText();
            Date inicioCursO = Formatacao.transformarStringEmDate(inicioCurso);
            java.sql.Date sqlDateInicioCurso = Formatacao.transformarDateEmDateSql(inicioCursO);        

            String terminoCurso= jFormattedTextFieldTermCursoCadastrar.getText();
            Date terminoCursO = Formatacao.transformarStringEmDate(inicioCurso);
            java.sql.Date sqlDateTermCurso = Formatacao.transformarDateEmDateSql(terminoCursO);   

            Aluno aluno = new Aluno();
            aluno.setNome(nome);
            aluno.setCpf(cpf);
            aluno.setEmail(email);
            aluno.setTelefone(telefone);        
            aluno.setIdCurso(idCurso);
            aluno.setDataNascimento(sqlDateNasc);
            aluno.setInicioCursoAluno(sqlDateInicioCurso);
            aluno.setTerminoCursoAluno(sqlDateInicioCurso);
            aluno.setStatusAluno(status);           
            
            
            if(Validacao.validaCPF(aluno.getCpf())){
                
                if(fachada.verificarExistenciaAlunoPorCpf(aluno.getCpf())){
                    JOptionPane.showMessageDialog(this,"Aluno já cadastrado no sitema.","VALIDAÇÃO",JOptionPane.ERROR_MESSAGE);
                    return;
                }else {
                    fachada.cadastrarAluno(aluno);
                    JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso.", "CONFIRMAÇÃO", JOptionPane.INFORMATION_MESSAGE);
                    
                    jTextFieldNomeCadastrar.setText("");
                    jFormattedTextFieldCpfCadastrar.setText("");       
                    jTextFieldEmail.setText("");                 
                    jTextFieldTelefone.setText("");     

                    jFormattedTextFieldDataNascCadastrar.setText("");
                    
                    jFormattedTextFieldInicioCursoCadastrar.setText("");
                    jFormattedTextFieldTermCursoCadastrar.setText("");
             
                    
                    return;
                    
                }
            } else {
                JOptionPane.showMessageDialog(this,"CPF inválido.","VALIDAÇÃO",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this,"Preencha todos os campos corretamente.","VALIDAÇÃO",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jComboBoxStatusEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusEditarActionPerformed

    private void jTextFieldNomeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlunos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisar1;
    private javax.swing.JButton botaoVoltar5;
    private javax.swing.JButton botaoVoltar6;
    private javax.swing.JButton botaoVoltar9;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluirAluno;
    private javax.swing.JButton btnPesquisarCpfEditar;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JFormattedTextField campoCpfPesquisaVisualizar;
    private javax.swing.JPanel guiaCadastrarAluno;
    private javax.swing.JPanel guiaEditarAluno;
    private javax.swing.JPanel guiaVisualizarAluno;
    private javax.swing.JTabbedPane guiasAluno;
    private javax.swing.JComboBox jComboBoxCursoCadastrar;
    private javax.swing.JComboBox jComboBoxCursoEditar;
    private javax.swing.JComboBox jComboBoxStatusCadastrar;
    private javax.swing.JComboBox jComboBoxStatusEditar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfEditar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascEditar;
    private javax.swing.JFormattedTextField jFormattedTextFieldInicioCursoCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextFieldInicioCursoEditar;
    private javax.swing.JFormattedTextField jFormattedTextFieldTermCursoCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextFieldTermCursoEditar;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JFormattedTextField jTextFieldEmailEditar;
    private javax.swing.JTextField jTextFieldNomeCadastrar;
    private javax.swing.JTextField jTextFieldNomeEditar;
    private javax.swing.JFormattedTextField jTextFieldTelefone;
    private javax.swing.JFormattedTextField jTextFieldTelefoneEditar;
    private javax.swing.JLabel lblCartao;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblInicioCurso;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblStatusAluno;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTerminoCurso;
    private javax.swing.JPanel painelConsulta1;
    private javax.swing.JPanel painelConsulta2;
    private javax.swing.JLabel tituloAlunos1;
    private javax.swing.JLabel tituloAlunos2;
    private javax.swing.JLabel tituloAlunos3;
    private javax.swing.JLabel tituloCadastrar;
    private javax.swing.JLabel tituloConsultar1;
    private javax.swing.JLabel tituloConsultar2;
    private javax.swing.JLabel tituloCpf3;
    private javax.swing.JLabel tituloCpf4;
    private javax.swing.JLabel tituloCpf5;
    private javax.swing.JLabel tituloCpf6;
    private javax.swing.JLabel tituloCpf7;
    private javax.swing.JLabel tituloCurso10;
    private javax.swing.JLabel tituloCurso11;
    private javax.swing.JLabel tituloCurso12;
    private javax.swing.JLabel tituloCurso13;
    private javax.swing.JLabel tituloCurso14;
    private javax.swing.JLabel tituloCurso2;
    private javax.swing.JLabel tituloCurso3;
    private javax.swing.JLabel tituloCurso4;
    private javax.swing.JLabel tituloCurso5;
    private javax.swing.JLabel tituloCurso6;
    private javax.swing.JLabel tituloCurso7;
    private javax.swing.JLabel tituloCurso8;
    private javax.swing.JLabel tituloCurso9;
    private javax.swing.JLabel tituloDataNasc10;
    private javax.swing.JLabel tituloDataNasc2;
    private javax.swing.JLabel tituloDataNasc3;
    private javax.swing.JLabel tituloDataNasc4;
    private javax.swing.JLabel tituloDataNasc5;
    private javax.swing.JLabel tituloDataNasc6;
    private javax.swing.JLabel tituloDataNasc7;
    private javax.swing.JLabel tituloDataNasc8;
    private javax.swing.JLabel tituloDataNasc9;
    private javax.swing.JLabel tituloNome2;
    private javax.swing.JLabel tituloNome3;
    private javax.swing.JLabel tituloNome4;
    private javax.swing.JLabel tituloVisualizarFunc;
    private javax.swing.JLabel tituloVisualizarFunc1;
    private javax.swing.JFormattedTextField txtPesquisarCpfEditar;
    // End of variables declaration//GEN-END:variables
}
